WIP

diff --git a/salt/files/usr/local/bin/sendPassiveCheck b/salt/files/usr/local/bin/sendPassiveCheck
--- a/salt/files/usr/local/bin/sendPassiveCheck
+++ b/salt/files/usr/local/bin/sendPassiveCheck
@@ -1,8 +1,11 @@
 #!/bin/bash
 
 cmd=$(basename $0)
-syntax="$cmd : [-f from-host] [-h] {-t to-host} {-s service} -n -v {-l {0|1|2}} [message]
+syntax="$cmd : [-f from-host] [-h] {-t to-host} {-s service} [-m maxtries] [-n] [-w window] [-v] {-l {0|1|2}} [message]
 $cmd : [-f from-host] -H {-t to-host} [-h] {-l {0|1|2}} -n -v [message]"
+
+Window=30
+MaxTries=10
 
 opt_f=$(hostname)
 opt_l=0
@@ -15,17 +18,17 @@ function sys {
 function sendPassiveCheck {
 	if [ -n "$opt_H" ]
 	then
-		sys echo "[$(date +%s)] PROCESS_HOST_CHECK_RESULT;${opt_f};${opt_l};$@" | ssh -x -T "$opt_t"
+		sys echo "[$(date +%s)] PROCESS_HOST_CHECK_RESULT;${opt_f};${opt_l};$@" | ssh -T "$opt_t"
 	else
-		sys echo "[$(date +%s)] PROCESS_SERVICE_CHECK_RESULT;${opt_f};${opt_s};${opt_l};$@" | ssh -x -T "$opt_t"
+		sys echo "[$(date +%s)] PROCESS_SERVICE_CHECK_RESULT;${opt_f};${opt_s};${opt_l};$@" | ssh -T "$opt_t"
 	fi
 }
 
 
-while getopts f:Hhl:ns:t:v arg
-do
+while getopts f:Hhl:m:ns:t:w:v arg
+	do
 	case "$arg" in
-		f|H|h|l|n|s|t|v)
+		f|H|h|l|m|n|s|t|w|v)
 			eval "opt_${arg}='${OPTARG:=1}'"
 			;;
 	esac
@@ -58,7 +61,37 @@ then
 	host="$opt_f"
 fi
 
-sendPassiveCheck "$@"
+if [ -n "$opt_m" ]
+then
+	MaxTries="$opt_m"
+fi
+
+if [ -n "$opt_w" ]
+then
+	Window="$opt_w"
+fi
+
+Tries=0
+res=$(sendPassiveCheck "$@" 2>&1)
+ReturnCode="$?"
+while [ "$ReturnCode" != 0 ]
+do
+	if [ "$Tries" -ge "$MaxTries" ]
+	then
+		logger -t "${cmd}" -- "Tried more than '$MaxTries' giving up. SendPassiveCheck $@"
+		break
+	else
+		Tries=$((Tries + 1))
+	fi
+
+	p=$(($RANDOM % $Window))
+	logger -t "${cmd}" -- "sendPassiveCheck $@ : ReturnCode = '$ReturnCode' failed with '$res'.  Pausing for $p seconds"
+
+	sleep "${p}s"
+
+	res=$(sendPassiveCheck "$@" 2>&1)
+	ReturnCode="$?"
+done
 
 # *** could set server to 'HostCheck' and combine service and host checks.
 if [ -n "$opt_H" ]
@@ -67,3 +100,4 @@ then
 else
 	logger -t "${cmd}:${opt_s}" -- "$@"
 fi
+
